# Generated by Django 5.0.2 on 2024-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='subscription_type',
            field=models.IntegerField(choices=[(1, 'Pro'), (2, 'Scale'), (3, 'Enterprise')]),
        ),
    ]
