# Generated by Django 5.0.2 on 2024-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='challenges',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='objective',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='size',
            field=models.CharField(default=123, max_length=35),
            preserve_default=False,
        ),
    ]
