# Generated by Django 5.0.2 on 2024-04-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspace_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='challenges',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='objective',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='size',
            field=models.CharField(default='xyz', max_length=50),
            preserve_default=False,
        ),
    ]
