# Generated by Django 5.0.2 on 2024-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_workspace_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='subscription_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Pro'), (2, 'Scale'), (3, 'Enterprise')], null=True),
        ),
    ]
