# Generated by Django 5.0.2 on 2024-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_workspaceinvite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='assistant_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
