# Generated by Django 5.0.2 on 2024-08-07 08:00

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.IntegerField(blank=True, choices=[(1, 'Pro'), (2, 'Scale'), (3, 'Enterprise')], null=True)),
                ('business_name', models.CharField(max_length=80)),
                ('website_url', models.URLField(unique=True)),
                ('industry', models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Media', 'Media'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive')], max_length=60, null=True)),
                ('assistant_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_space_root_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Media', 'Media'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive')], max_length=80)),
                ('pinecone_namespace', models.CharField(default=workspaces.models.create_namespace_id, max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkSpaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=workspaces.models.create_workspace_invite, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
    ]
