
# Generated by Django 5.0.2 on 2024-04-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='size',
        ),
    ]
