# Generated by Django 5.0.2 on 2024-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subspace',
            name='industry',
            field=models.CharField(choices=[(1, 'Retail'), (2, 'Hospitality'), (3, 'Media'), (4, 'Technology'), (5, 'Finance'), (6, 'Sport'), (7, 'Beauty'), (8, 'Automotive')], max_length=80),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='industry',
            field=models.CharField(blank=True, choices=[(1, 'Retail'), (2, 'Hospitality'), (3, 'Media'), (4, 'Technology'), (5, 'Finance'), (6, 'Sport'), (7, 'Beauty'), (8, 'Automotive')], max_length=60, null=True),
        ),
    ]
