# Generated by Django 5.0.2 on 2024-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_subspace_industry_alter_workspace_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subspace',
            name='industry',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Media', 'Media'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive')], max_length=80),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='industry',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Media', 'Media'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Automotive', 'Automotive')], max_length=60, null=True),
        ),
    ]
