# Generated by Django 5.0.2 on 2024-07-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_subspace_industry_alter_workspace_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subspace',
            name='country',
        ),
    ]
