# Generated by Django 5.0.2 on 2024-08-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_remove_subspace_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='pinecone_namespace',
        ),
    ]
