# Generated by Django 5.0.2 on 2024-05-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspace_assistant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='industry',
            field=models.CharField(blank=True, choices=[('\u2060Retail', '\u2060Retail'), ('\u2060Hospitality', '\u2060Hospitality'), ('\u2060Media', '\u2060Media'), ('\u2060Technology', '\u2060Technology'), ('\u2060Finance', '\u2060Finance'), ('\u2060Sport', '\u2060Sport'), ('\u2060Beauty', '\u2060Beauty'), ('\u2060Automotive', '\u2060Automotive')], max_length=60, null=True),
        ),
    ]
