# Generated by Django 5.0.2 on 2024-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_workspace_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='business_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
