# Generated by Django 5.0.2 on 2024-06-20 12:55

import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_alter_workspace_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='pinecone_namespace',
            field=models.CharField(default=workspaces.models.create_namespace_id, max_length=50),
        ),
    ]
