# Generated by Django 5.0.2 on 2024-08-03 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='ws_channel_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
