# Generated by Django 5.0.2 on 2024-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Technical', 'Technical'), ('To improve', 'To improve'), ('Feedback', 'Feedback'), ('Others', 'Others')], max_length=30),
        ),
    ]
