# Generated by Django 5.0.2 on 2024-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='idk', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='emoji',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
