# Generated by Django 5.0.2 on 2024-03-14 09:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Channel-Logo', validators=[django.core.validators.validate_image_file_extension])),
                ('name', models.CharField(max_length=40)),
                ('basic_info', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.credential')),
            ],
        ),
    ]
