# Generated by Django 5.0.2 on 2024-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='convo',
            name='title',
            field=models.CharField(default='New Chat', max_length=100),
        ),
    ]
