# Generated by Django 5.0.2 on 2024-03-16 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team'),
        ),
        migrations.AddField(
            model_name='channel',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.credential'),
        ),
    ]
