# Generated by Django 5.0.2 on 2024-04-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_rename_promptinput_prompt_promptfeedback_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='refactored_text',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='response_image',
        ),
    ]
