# Generated by Django 5.0.2 on 2024-04-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_convo_archived_alter_convo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convo',
            options={'ordering': ['-id']},
        ),
    ]
