# Generated by Django 5.0.2 on 2024-04-02 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_promptinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptinput',
            options={'ordering': ['author', 'id']},
        ),
        migrations.RenameField(
            model_name='promptinput',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='promptinput',
            old_name='query',
            new_name='text_query',
        ),
        migrations.RemoveField(
            model_name='promptinput',
            name='created',
        ),
        migrations.RemoveField(
            model_name='promptinput',
            name='refactored_query',
        ),
        migrations.AddField(
            model_name='promptinput',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promptinput',
            name='image_query',
            field=models.ImageField(blank=True, null=True, upload_to='Prompts-Query/'),
        ),
        migrations.AddField(
            model_name='promptinput',
            name='refactored_text',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='promptinput',
            name='response_image',
            field=models.ImageField(blank=True, null=True, upload_to='Response-Image/'),
        ),
        migrations.AlterField(
            model_name='promptinput',
            name='response_text',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
