# Generated by Django 5.0.2 on 2024-03-24 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channel_unique_together'),
        ('workspaces', '0002_alter_workspace_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptfeedback',
            name='channel',
        ),
        migrations.AddField(
            model_name='channel',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='key_1',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='key_2',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='key_3',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='key_4',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PromptInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=10000)),
                ('refactored_query', models.TextField(max_length=20000)),
                ('response_text', models.TextField(max_length=20000)),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
    ]
