# Generated by Django 5.0.2 on 2024-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_convo_assistant_id_convo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='image_query',
        ),
        migrations.AddField(
            model_name='prompt',
            name='file_query',
            field=models.FileField(blank=True, null=True, upload_to='Prompts-File/'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='response_image',
            field=models.ImageField(blank=True, null=True, upload_to='Response-Image/'),
        ),
    ]
