# Generated by Django 5.0.2 on 2024-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_promptfeedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptfeedback',
            name='category',
            field=models.CharField(choices=[('1', "Don't like the style"), ('2', 'Not factually correct'), ('3', 'Being Lazy'), ('4', 'Other')], max_length=60),
        ),
    ]
