# Generated by Django 5.0.2 on 2024-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_alter_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('9#0EE90', '#90EE90'), ('#FFCCCC', '#FFCCCC'), ('#D3D3D3', '#D3D3D3'), ('#E6E6FA', '#E6E6FA'), ('#ADD8E6', '#ADD8E6')], default='#ADD8E6', max_length=30),
        ),
    ]
