# Generated by Django 5.0.2 on 2024-04-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_alter_blocknote_image_alter_blocknote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='blocknote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.blocknote'),
        ),
    ]
