# Generated by Django 5.0.2 on 2024-06-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_activated_remove_channel_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='table_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
