# Generated by Django 5.0.2 on 2024-05-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_knowledgebase'),
        ('workspaces', '0002_remove_workspace_challenges_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['workspace', 'user', '-created_at'], 'verbose_name_plural': 'KnowledgeBase'},
        ),
        migrations.AddField(
            model_name='blocknote',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
