# Generated by Django 5.0.2 on 2024-06-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_prompt_table_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='response_text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
