# Generated by Django 5.0.2 on 2024-05-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_alter_knowledgebase_options_blocknote_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocknote',
            name='image',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
