# Generated by Django 5.0.2 on 2024-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_alter_blocknote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
