# Generated by Django 5.0.2 on 2024-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_alter_blocknote_image_alter_channel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.IntegerField(choices=[(1, 'Google ads'), (2, 'Meta'), (3, 'X (Twitter)'), (4, 'Linkedin'), (5, 'TikTok'), (6, 'Reddit'), (7, 'Shopify'), (8, 'Google-Analytics'), (9, 'MailChimp'), (10, 'Instagram')]),
        ),
    ]
