# Generated by Django 5.0.2 on 2024-05-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_prompt_chart_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convo',
            old_name='assistant_id',
            new_name='thread_id',
        ),
    ]
