# Generated by Django 5.0.2 on 2024-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0013_rename_assistant_id_convo_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='key_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
