# Generated by Django 5.0.2 on 2024-06-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_alter_blocknote_image'),
        ('channels', '0013_alter_channel_channel_type'),
    ]

    operations = [
    ]
