# Generated by Django 5.0.2 on 2024-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_apicredentials_key_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.IntegerField(choices=[(1, 'Red'), (2, 'Green')])),
            ],
        ),
        migrations.AddField(
            model_name='blocknote',
            name='note',
            field=models.ManyToManyField(to='channels.note'),
        ),
    ]
