# Generated by Django 5.0.2 on 2024-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0015_note_blocknote_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='blocknote',
        ),
        migrations.AddField(
            model_name='prompt',
            name='blocknote',
            field=models.ManyToManyField(to='channels.blocknote'),
        ),
    ]
