# Generated by Django 5.0.2 on 2024-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0017_alter_apicredentials_key_1_alter_prompt_blocknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocknote',
            name='note',
            field=models.ManyToManyField(blank=True, null=True, to='channels.note'),
        ),
    ]
