# Generated by Django 5.0.2 on 2024-05-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0018_alter_blocknote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='prompt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channels.prompt'),
            preserve_default=False,
        ),
    ]
