# Generated by Django 5.0.2 on 2024-05-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0019_note_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocknote',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='blocknote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channels.blocknote'),
            preserve_default=False,
        ),
    ]
