# Generated by Django 5.0.2 on 2024-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0021_alter_channel_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredentials',
            name='key_1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
