# Generated by Django 5.0.2 on 2024-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0026_alter_apicredentials_key_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='key_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
