# Generated by Django 5.0.2 on 2024-05-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0027_apicredentials_key_6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='blocknote',
        ),
    ]
