# Generated by Django 5.0.2 on 2024-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0028_remove_prompt_blocknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptfeedback',
            name='category',
            field=models.CharField(choices=[(1, "Don't like the style"), (2, 'Not factually correct'), (3, 'Being Lazy'), (4, 'Other')], max_length=60),
        ),
    ]
