# Generated by Django 5.0.2 on 2024-08-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_channels.tags'),
            preserve_default=False,
        ),
    ]
