# Generated by Django 5.0.2 on 2024-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_referral_code_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
    ]
