# Generated by Django 5.0.2 on 2024-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredentials',
            name='key_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='key_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='key_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
