# Generated by Django 5.0.2 on 2024-05-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_apicredentials_key_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='note_text',
        ),
    ]
