# Generated by Django 5.0.2 on 2024-06-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_convo_options_rename_note_note_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.IntegerField(choices=[(1, 'Google ads'), (2, 'Meta'), (3, 'X (Twitter)'), (4, 'Linkedin'), (5, 'TikTok'), (6, 'Reddit')]),
        ),
    ]
