# Generated by Django 5.0.2 on 2024-06-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptfeedback',
            name='category',
            field=models.IntegerField(choices=[(1, "Don't like the style"), (2, 'Not factually correct'), (3, 'Being Lazy'), (4, 'Other')]),
        ),
    ]
