# Generated by Django 5.0.2 on 2024-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_promptfeedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.IntegerField(choices=[(1, '#90EE90'), (2, '#FFCCCC'), (3, '#D3D3D3'), (4, '#E6E6FA'), (5, '#ADD8E6')]),
        ),
    ]
