# Generated by Django 5.0.2 on 2024-06-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_alter_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.IntegerField(choices=[(1, 'Google ads'), (2, 'Meta'), (3, 'X (Twitter)'), (4, 'Linkedin'), (5, 'TikTok'), (6, 'Reddit'), (7, 'Shopify')]),
        ),
    ]
