# Generated by Django 5.0.2 on 2024-06-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_alter_channel_channel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='connected',
        ),
    ]
