# Generated by Django 5.0.2 on 2024-06-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0013_alter_channel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#90EE90', '#90EE90'), ('#FFCCCC', '#FFCCCC'), ('#D3D3D3', '#D3D3D3'), ('#E6E6FA', '#E6E6FA'), ('#ADD8E6', '#ADD8E6')], default='#ADD8E6', max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.CharField(max_length=500),
        ),
    ]
