# Generated by Django 5.0.2 on 2024-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_alter_note_color_alter_note_note_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='chart_data',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='response_image',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='table_data',
        ),
        migrations.AddField(
            model_name='prompt',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='Response-File/'),
        ),
    ]
