# Generated by Django 5.0.2 on 2024-08-05 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0015_remove_prompt_chart_data_and_more'),
        ('workspaces', '0012_alter_subspace_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['workspace', '-created_at'], 'verbose_name_plural': 'KnowledgeBase'},
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='file',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='title',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='user',
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='knowledge_source',
            field=models.ManyToManyField(blank=True, null=True, to='channels.knowledgesource'),
        ),
    ]
