# Generated by Django 5.0.2 on 2024-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Do you want to receive the newsletter?'),
        ),
    ]
