# Generated by Django 5.0.2 on 2024-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='industry',
            field=models.CharField(blank=True, choices=[('E-commerce', 'E-commerce'), ('Sales', 'Sales'), ('Enterprise', 'Enterprise')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='website_url',
            field=models.URLField(unique=True),
        ),
    ]
