# Generated by Django 5.0.2 on 2024-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_team_member',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Indie'), (2, 'Pro'), (3, 'Scale'), (4, 'Team member')], null=True),
        ),
    ]
