# Generated by Django 5.0.2 on 2024-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Indie'), (2, 'Pro'), (3, 'Scale'), (4, 'Team member (15$)'), (5, 'Team member (20$)')], null=True),
        ),
    ]
