# Generated by Django 5.0.2 on 2024-03-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Indie'), (2, 'Pro'), (3, 'Scale'), (4, 'Team member')], null=True),
        ),
    ]
